# Generated by Django 3.0.6 on 2020-05-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lucky_draw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='table_number',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='ticket_number',
            field=models.IntegerField(default=7781, unique=True),
        ),
        migrations.AlterField(
            model_name='draw',
            name='number_of_winners',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_number_of_winners',
            field=models.IntegerField(default=67),
        ),
    ]
